### ISSUE TITLE
The `last_sync_time` is not updated.

### ISSUE THREAD

**Issue by matt-hobbs-prima** [statsig-io/erlang-sdk#23]
When further flushes are completed, the genservers `last_sync_time` state is not updated.
This should happen around here (statsig_server.erl)
```
handle_info(download_specs, [{log_events, Events}, {api_key, ApiKey}, {last_sync_time, Time}]) ->
  case network:request(ApiKey, "download_config_specs", #{<<"sinceTime">> => Time}) of
    false -> unknown;
    Body -> parse_and_save_specs(Body)
```
instead the original state time is used.

**Comment by tore-statsig** [comment]
Ah interesting.  We actually have a test case for this so I was surprised to see the issue - but the test case only checks that the first sync sets time to 0, and the second sync updates the time.  But in this case, its any sync *after* that.

I can correct this

**Comment by tore-statsig** [comment]
To be clear - this wont impact the sdk that much - it will redownload the entire rule definition every time, but everything should be working.  Testing the fix now though

**Comment by tore-statsig** [comment]
fixed in https://github.com/statsig-io/erlang-sdk/commit/cd16a281a885c870aabd8f108453fe3f281405ec
